import type {
  CaptureDefinition,
  CaptureScenario,
  CaptureViewport,
  CaptureViewportSet,
} from "./capture-types"

export const primaryViewport: CaptureViewport = {
  height: 844,
  label: "mobile-390",
  width: 390,
}

export const criticalViewports: CaptureViewport[] = [
  { height: 568, label: "mobile-320", width: 320 },
  { height: 800, label: "mobile-360", width: 360 },
  primaryViewport,
  { height: 932, label: "mobile-430", width: 430 },
]

/*
 * 2560 is here because nothing was ever looked at above 1440, which is how a
 * content column capped at a flat 1240px sat unnoticed on large monitors: every
 * gate rendered at a width where the cap is invisible, so "everything looks
 * small on 4K" could not be seen, let alone regressed against. It captures a
 * screenshot for human review and asserts nothing on its own.
 */
export const responsiveViewports: CaptureViewport[] = [
  { height: 1440, label: "wide-2560", width: 2560 },
  { height: 900, label: "web-1440", width: 1440 },
  { height: 1024, label: "tablet-820", width: 820 },
  primaryViewport,
]

const populatedScenarios: CaptureScenario[] = [
  "enrollments",
  "schedules",
  "loaded",
]

const scheduledScenarios: CaptureScenario[] = ["schedules", "loaded"]

const reportScenarios: CaptureScenario[] = ["loaded"]

export const captureDefinitions: CaptureDefinition[] = [
  {
    actor: "guest",
    critical: true,
    description: "Complete logged-out public academy homepage",
    id: "public-home-default",
    route: "/",
  },
  {
    actions: ["public-mobile-menu-open"],
    actor: "guest",
    critical: true,
    description: "Public mobile navigation open",
    id: "public-home-mobile-menu",
    narrowOnly: true,
    route: "/",
    viewportOnly: true,
  },
  {
    actions: ["profile-menu-open"],
    actor: "coach",
    description: "Logged-in coach account menu on the public homepage",
    id: "public-home-coach-account-menu",
    route: "/",
    viewportOnly: true,
  },
  {
    actions: ["profile-menu-open"],
    actor: "player",
    description: "Logged-in player account menu on the public homepage",
    id: "public-home-player-account-menu",
    route: "/",
    scenarios: populatedScenarios,
    viewportOnly: true,
  },
  {
    actions: ["public-nav-academy"],
    actor: "guest",
    description: "Academy navigation anchor landing position",
    focusSelector: "#academy",
    id: "public-home-academy-anchor",
    narrowOnly: true,
    route: "/",
    viewportOnly: true,
  },
  {
    actions: ["public-nav-programs"],
    actor: "guest",
    description: "Programs navigation anchor landing position",
    focusSelector: "#programs",
    id: "public-home-programs-anchor",
    narrowOnly: true,
    route: "/",
    viewportOnly: true,
  },
  {
    actions: ["public-nav-why"],
    actor: "guest",
    description: "Why SMBA navigation anchor landing position",
    focusSelector: "#why-smba",
    id: "public-home-why-anchor",
    narrowOnly: true,
    route: "/",
    viewportOnly: true,
  },
  {
    actions: ["public-nav-trial"],
    actor: "guest",
    description: "Free-trial navigation anchor landing position",
    focusSelector: "#trial",
    id: "public-home-trial-anchor",
    narrowOnly: true,
    route: "/",
    viewportOnly: true,
  },
  {
    actions: ["public-nav-contact"],
    actor: "guest",
    description: "Contact navigation anchor landing position",
    focusSelector: "#contact",
    id: "public-home-contact-anchor",
    narrowOnly: true,
    route: "/",
    viewportOnly: true,
  },
  {
    actions: ["public-fee-weekday-standard"],
    actor: "guest",
    description: "Weekday Intermediate four-day fee selection",
    focusSelector: ".fee-explorer",
    id: "public-fee-weekday-standard",
    route: "/",
    viewportOnly: true,
  },
  {
    actions: ["public-fee-weekday-advanced"],
    actor: "guest",
    description: "Weekday Advanced fee selection with its constrained frequency",
    focusSelector: ".fee-explorer",
    id: "public-fee-weekday-advanced",
    route: "/",
    viewportOnly: true,
  },
  {
    actions: ["public-fee-weekend"],
    actor: "guest",
    description: "Weekend Adult fee selection without weekday frequency controls",
    focusSelector: ".fee-explorer",
    id: "public-fee-weekend",
    route: "/",
    viewportOnly: true,
  },
  {
    actions: ["public-trial-filled"],
    actor: "guest",
    description: "Free-trial form with representative selected values",
    focusSelector: ".trial-form-card",
    id: "public-trial-form-filled",
    route: "/",
    viewportOnly: true,
  },
  {
    actions: ["public-trial-popup-blocked"],
    actor: "guest",
    description: "Free-trial safe fallback when WhatsApp popup is blocked",
    focusSelector: ".trial-form-card .form-reassurance",
    id: "public-trial-popup-blocked",
    route: "/",
    viewportOnly: true,
  },
  {
    actor: "guest",
    critical: true,
    description: "Shared Academy ID login screen",
    id: "login-default",
    route: "/login",
  },
  {
    actions: ["login-format-error"],
    actor: "guest",
    description: "Login format validation feedback",
    id: "login-format-error",
    route: "/login",
    viewportOnly: true,
  },
  {
    actions: ["login-account-not-found"],
    actor: "guest",
    description: "Login account-not-found feedback",
    id: "login-account-not-found",
    route: "/login",
    viewportOnly: true,
  },
  {
    actor: "guest",
    critical: true,
    description: "Player registration screen",
    id: "register-default",
    route: "/register",
  },
  {
    actions: ["register-validation-error"],
    actor: "guest",
    description: "Registration validation feedback",
    id: "register-validation-error",
    route: "/register",
    viewportOnly: true,
  },
  {
    actor: "coach",
    description: "Coach dashboard in its initial state",
    id: "coach-dashboard-default",
    route: "/coach",
  },
  {
    actions: ["profile-menu-open"],
    actor: "coach",
    description: "Coach account menu open",
    id: "coach-dashboard-account-menu",
    route: "/coach",
  },
  {
    actor: "coach",
    critical: true,
    description: "Read-only player attendance register workspace",
    id: "coach-attendance-open",
    route: "/coach/attendance/players/register",
  },
  {
    actions: ["attendance-year-start"],
    actor: "coach",
    description: "Occurrence attendance register scrolled to the start of the year",
    id: "coach-attendance-year-start",
    route: "/coach/attendance/players/register",
    scenarios: scheduledScenarios,
  },
  {
    actions: ["attendance-weekend-adult"],
    actor: "coach",
    description: "Attendance register with Weekend Adult selected",
    focusSelector: "#attendance-register",
    id: "coach-attendance-weekend-adult",
    route: "/coach/attendance/players/register",
    scenarios: scheduledScenarios,
    viewportOnly: true,
  },
  {
    actor: "coach",
    critical: true,
    description: "Player attendance recorder before a session is selected",
    id: "coach-attendance-record",
    route: "/coach/attendance/players/record?date={referenceDate}",
    scenarios: scheduledScenarios,
  },
  {
    actions: ["attendance-session-selected"],
    actor: "coach",
    critical: true,
    description: "Player attendance recorder with one eligible session roster selected",
    id: "coach-attendance-record-session",
    route: "/coach/attendance/players/record?date={referenceDate}",
    scenarios: scheduledScenarios,
  },
  {
    actor: "coach",
    critical: true,
    description: "Read-only staff attendance register",
    id: "coach-staff-attendance-register",
    route: "/coach/attendance/staff/register",
    scenarios: populatedScenarios,
  },
  {
    actor: "coach",
    critical: true,
    description: "Daily staff roll-call workspace",
    id: "coach-staff-roll-call",
    route: "/coach/attendance/staff/record?date={referenceDate}",
    scenarios: populatedScenarios,
  },
  {
    actor: "coach",
    critical: true,
    description: "Dedicated attendance rescheduling workspace",
    id: "coach-attendance-adjustments",
    route: "/coach/attendance/adjustments",
    scenarios: ["loaded"],
  },
  {
    actions: ["adjustment-player-selected"],
    actor: "coach",
    critical: true,
    description: "Missed-session month calendar after player selection",
    id: "coach-attendance-adjustment-calendar",
    route: "/coach/attendance/adjustments",
    scenarios: ["loaded"],
  },
  {
    actions: ["adjustment-player-selected", "adjustment-source-selected"],
    actor: "coach",
    critical: true,
    description: "Missed session selected with completion-date choices revealed",
    focusSelector: ".coach-adjustment-editor",
    id: "coach-attendance-adjustment-source-selected",
    route: "/coach/attendance/adjustments",
    scenarios: ["loaded"],
    viewportOnly: true,
  },
  {
    actor: "coach",
    description: "Session calendar mobile day view",
    id: "coach-calendar-day",
    route: "/coach/calendar?date={referenceDate}",
  },
  {
    actions: ["calendar-month"],
    actor: "coach",
    description: "Session calendar mobile month view",
    id: "coach-calendar-month",
    route: "/coach/calendar?date={referenceDate}",
  },
  {
    actions: ["calendar-session-open"],
    actor: "coach",
    critical: true,
    description: "Session calendar occurrence and roster detail open",
    id: "coach-calendar-session-open",
    route: "/coach/calendar?date={referenceDate}",
    scenarios: scheduledScenarios,
  },
  {
    actions: ["calendar-replacement-open"],
    actor: "coach",
    description: "Future calendar occurrence with replacement controls open",
    focusSelector: ".coach-occurrence-actions details[open]",
    id: "coach-calendar-replacement-open",
    route: "/coach/calendar?date=2026-08-04",
    scenarios: scheduledScenarios,
    viewportOnly: true,
  },
  {
    actor: "coach",
    description: "Calendar day view with no scheduled occurrences",
    id: "coach-calendar-empty-day",
    route: "/coach/calendar?date=2027-01-01",
  },
  {
    actor: "coach",
    description: "Schedules and rosters initial state",
    id: "coach-schedules-default",
    route: "/coach/schedules",
  },
  {
    actor: "coach",
    description: "New recurring schedule form open",
    id: "coach-schedule-create",
    route: "/coach/schedules/new",
  },
  {
    actions: ["schedule-create-weekend"],
    actor: "coach",
    description: "New recurring Weekend Adult schedule with representative selections",
    focusSelector: ".coach-series-form",
    id: "coach-schedule-create-weekend",
    route: "/coach/schedules/new",
    viewportOnly: true,
  },
  {
    actions: ["schedule-programmes-collapse"],
    actor: "coach",
    description: "Schedules with all programme groups collapsed",
    id: "coach-schedules-collapsed",
    route: "/coach/schedules",
    scenarios: scheduledScenarios,
  },
  {
    actions: ["schedule-roster-open"],
    actor: "coach",
    critical: true,
    description: "First recurring schedule roster detail open",
    id: "coach-schedule-roster-open",
    route: "/coach/schedules",
    scenarios: scheduledScenarios,
  },
  {
    actions: ["schedule-roster-player-selected"],
    actor: "coach",
    critical: true,
    description: "Roster assignment with an eligible player and weekday controls revealed",
    focusSelector: ".coach-roster-assign",
    id: "coach-schedule-roster-player-selected",
    route: "/coach/schedules",
    scenarios: scheduledScenarios,
    viewportOnly: true,
  },
  {
    actor: "coach",
    critical: true,
    description: "Member directory initial state",
    id: "coach-members-default",
    route: "/coach/members",
  },
  {
    actions: ["member-filters-open"],
    actor: "coach",
    description: "Member directory filters open",
    id: "coach-member-filters-open",
    narrowOnly: true,
    route: "/coach/members",
  },
  {
    actions: ["member-filter-applied"],
    actor: "coach",
    description: "Member directory with Level, Status, and Batch filters applied",
    focusSelector: ".coach-member-directory-controls",
    id: "coach-member-filter-applied",
    narrowOnly: true,
    route: "/coach/members",
    scenarios: populatedScenarios,
    viewportOnly: true,
  },
  {
    actions: ["member-details-open"],
    actor: "coach",
    critical: true,
    description: "First member record detail open",
    id: "coach-member-details-open",
    route: "/coach/members",
    scenarios: populatedScenarios,
  },
  {
    actions: ["member-contact-reveal"],
    actor: "coach",
    description: "Member record with primary contact revealed",
    focusSelector: ".coach-member-detail-panel",
    id: "coach-member-contact-revealed",
    route: "/coach/members",
    scenarios: populatedScenarios,
    viewportOnly: true,
  },
  {
    actions: ["member-edit-open"],
    actor: "coach",
    critical: true,
    description: "Member profile and training edit form",
    focusSelector: ".coach-member-detail-panel",
    id: "coach-member-edit-form",
    route: "/coach/members",
    scenarios: populatedScenarios,
    viewportOnly: true,
  },
  {
    actor: "coach",
    description: "Monthly report workspace initial state",
    id: "coach-reports-default",
    route: "/coach/reports/write?month={reportMonth}",
  },
  {
    actions: ["report-checklist-collapse"],
    actor: "coach",
    critical: true,
    description: "Monthly report editor with the checklist collapsed",
    id: "coach-report-editor",
    route: "/coach/reports/write?month={reportMonth}",
    scenarios: reportScenarios,
  },
  {
    actions: ["report-checklist-collapse", "report-preview-open"],
    actor: "coach",
    critical: true,
    description: "Monthly report preview dialog open",
    id: "coach-report-preview",
    route: "/coach/reports/write?month={reportMonth}",
    scenarios: reportScenarios,
    viewportOnly: true,
  },
  {
    actor: "coach",
    critical: true,
    description: "Published monthly reports archive for all players",
    id: "coach-published-reports",
    route: "/coach/reports?period={reportMonth}",
    scenarios: reportScenarios,
  },
  {
    actions: ["coach-published-report-open"],
    actor: "coach",
    critical: true,
    description: "Focused immutable published report with revision history",
    id: "coach-published-report-detail",
    route: "/coach/reports?period={reportMonth}",
    scenarios: reportScenarios,
  },
  {
    actor: "coach",
    critical: true,
    description: "Coach rapid payment workspace scoped to outstanding players",
    id: "coach-financials-record-payment",
    route: "/coach/financials/record?scope=outstanding",
    scenarios: ["loaded"],
  },
  {
    actor: "coach",
    description: "Coach rapid payment lookup showing all players and non-payable states",
    id: "coach-financials-record-payment-all",
    route: "/coach/financials/record?scope=all",
    scenarios: ["loaded"],
  },
  {
    actor: "coach",
    critical: true,
    description: "Coach monthly Fee Register with the loaded academy ledger",
    id: "coach-financial-records-fees",
    route: "/coach/financials/records?view=fees&mode=monthly&period=2026-08&scope=active&status=all",
    scenarios: ["loaded"],
  },
  {
    actions: ["financial-player-record-open"],
    actor: "coach",
    description: "Focused player Fee Record opened from the monthly Fee Register",
    id: "coach-financials-player-record",
    route: "/coach/financials/records?view=fees&mode=monthly&period=2026-08&scope=active&status=all",
    scenarios: ["loaded"],
  },
  {
    actor: "coach",
    description: "Coach Collections Day Book for the loaded finance period",
    id: "coach-financial-records-collections",
    route: "/coach/financials/records?view=collections&from=2026-08-01&to=2026-08-31",
    scenarios: ["loaded"],
  },
  {
    actor: "coach",
    description: "Coach readable Financial Activity History",
    id: "coach-financial-records-activity",
    route: "/coach/financials/records?view=activity",
    scenarios: ["loaded"],
  },
  {
    actor: "player",
    critical: true,
    description: "Player dashboard in its initial state",
    id: "player-dashboard-default",
    route: "/player",
    scenarios: populatedScenarios,
  },
  {
    actor: "player",
    critical: true,
    description: "Player expanded attendance in the focused month calendar",
    focusSelector: "#player-attendance-register",
    id: "player-dashboard-attendance-calendar",
    route: "/player?attendance=register",
    scenarios: ["loaded"],
    segmentPolicy: "always",
  },
  {
    actions: ["profile-menu-open"],
    actor: "player",
    critical: true,
    description: "Player account menu open",
    id: "player-dashboard-account-menu",
    route: "/player",
    scenarios: populatedScenarios,
  },
  {
    actor: "player",
    description: "Player dashboard focused on the functional training-week workspace",
    focusSelector: "#training-week",
    id: "player-dashboard-training-week",
    route: "/player#training-week",
    scenarios: populatedScenarios,
    viewportOnly: true,
  },
  {
    actor: "player",
    description: "Player monthly reports initial state",
    id: "player-reports-default",
    route: "/player/reports",
    scenarios: populatedScenarios,
  },
  {
    actions: ["student-report-open"],
    actor: "player",
    critical: true,
    description: "Player latest monthly report expanded",
    id: "player-report-expanded",
    route: "/player/reports",
    scenarios: reportScenarios,
    segmentPolicy: "always",
  },
  {
    actor: "player",
    critical: true,
    description: "Player read-only Fee Record",
    id: "player-financials-default",
    route: "/player/financials",
    scenarios: ["loaded"],
  },
]

/* The widest window at which every `narrowOnly` control still exists. The public
 * navigation collapses to its toggle under `@media (max-width: 900px)` in
 * app/public-home.css, and the Member Directory filter toggle lives under
 * `@media (max-width: 980px)` at app/portal.css:11528. 900 satisfies both, and it
 * sits between tablet-820 and web-1440 so it splits the responsive set exactly
 * where the observed failures split it. */
const NARROW_CONTROL_CEILING = 900

export function viewportsForCapture(
  definition: CaptureDefinition,
  viewportSet: CaptureViewportSet = "mobile",
) {
  if (viewportSet === "responsive") {
    /* Without this, asking for the responsive set handed every definition all four
     * widths regardless of what it was written for, so the six public-home nav
     * captures and the two Member Directory filter captures ran at 1440 and 2560 --
     * where their control does not render -- and each spent the full 180s case
     * timeout waiting for it. Eight definitions failing by construction is why the
     * responsive set was never wired into a workflow, and why nothing in CI has ever
     * rendered a screen wider than 430px (.github/workflows/ui-accessibility.yml:191).
     */
    return definition.narrowOnly
      ? responsiveViewports.filter((viewport) => viewport.width <= NARROW_CONTROL_CEILING)
      : responsiveViewports
  }
  return definition.critical ? criticalViewports : [primaryViewport]
}
